### ISSUE TITLE
What to changes to watch for?

### ISSUE THREAD

**Issue by GodwinEbikwo** [toinelin/react-locomotive-scroll#16]
Hi @toinelin thanks for this package a lot, I wanted to know what props we should add to the provider to avoid any weird scroll behaviors.

**Comment by antoinelin** [comment]
Hi @GodwinEbikwo, sorry for the late late late reply 🙏🏻 I will take a bit of time asap to update the README to add more infos to it

**Comment by antoinelin** [comment]
Call for feedbacks : at this time, I used to watch location changes mainly. If you found other cases you faced in which you had to refresh the scroll instance, do not hesitate to share them here, I will had them to the README.
