### ISSUE TITLE
"the context is missing" warning printing before lib is loaded

### ISSUE THREAD

**Issue by fcisio** [toinelin/react-locomotive-scroll#17]
I've already flagged the code change responsible for this.

Basically, the warning is logged before `locomotive-scroll` is loaded. So the warning is irrelevant at that point since it's not in fact due to configuration or usage issues.

The warning should be adapted to only log after the lib is loaded.

**Comment by antoinelin** [comment]
Hi, thank you I will check that this week-end 🙏🏻🙏🏻🙏🏻

**Comment by andreuscafe** [comment]
Hi! Any updates on this issue? The warning is still logging every time I reload my nextJS app:

`the context is missing. You may be using the hook without registering LocomotiveScrollProvider, or you may be using the hook in a component which is not wrapped by LocomotiveScrollProvider.`

Although seems like everything is working fine.
