### ISSUE TITLE
Examples in nextJs?

### ISSUE THREAD

**Issue by tanshunyuan** [toinelin/react-locomotive-scroll#18]
Hi there, is it possible to include an example on how to setup react-locomotive-scroll in nextjs with both different directions included?

**Comment by antoinelin** [comment]
Hi, you can find a codesandbox [here](https://codesandbox.io/s/react-locomotive-scroll-vm8lt) on how to setup using Next.js.
I will not have the time to re-create the Locomotive Scroll documentation (or create multiple exemples) for a dedicated usage with React. Locomotive Scroll has not been developed with React specificities in mind and IMHO it may be smarter to take time to rethink the API entirely for a better DX for it.

**Comment by m90khan** [comment]
![image](https://user-images.githubusercontent.com/6104751/147246475-2fa21701-b45c-4f16-bf76-e3ba91455c3b.png)

I get this error in nextjs based on the codesanbox above. 

Any tip?

**Comment by m90khan** [comment]
The code sandbox example does not seem to work well inside nextjs project.
Does anyone have an example project in nextjs that I can have a look at?
@tanshunyuan . did you manage to work it out?
Thank you.

**Comment by Hensga** [comment]
I'm using the "normal" locomotive scroll --> [Locomotive](https://github.com/locomotivemtl/locomotive-scroll) inside my nextjs project. Then I import with useEffect as follows:

`useEffect(() => {
    import('locomotive-scroll').then((locomotiveModule) => {
      const ScrollEl = document.querySelector('#main-container');
      const scroll = new locomotiveModule.default({
        el: ScrollEl,
        smooth: true,
        multiplier: 1,
        class: 'is-reveal',
      });
    });
  }, []);
`


<img width="824" alt="Bildschirmfoto 2022-01-22 um 00 53 22" src="https://user-images.githubusercontent.com/56224913/150614512-7a8c4f2f-f093-4184-a7f2-2efc1cadc948.png">

Maybe this works here too? Or at least it gives you something new to think about :S

**Comment by ababurak92** [comment]
@Henzibit thanks for share it.Its inspired me for fix my problem.
