### ISSUE TITLE
Console warning. The context is missing

### ISSUE THREAD

**Issue by willslater** [toinelin/react-locomotive-scroll#19]
react-locomotive-scroll: the context is missing. You may be using the hook without registering LocomotiveScrollProvider, or you may be using the hook in a component which is not wrapped by LocomotiveScrollProvider. 

I get the message above in the console whilst using this in a Next JS project. It seems to work but I get a lot of these console warnings. 

The fact it works and I have actually got them wrapped its not a major issue but has anybody got the same issue?

**Comment by KyuubiKeith** [comment]
I got the same issue on console, a warning. Thought its my first time using this and I'm pretty new to the scene, I'm using it in NextJS and set up exactly like the sandbox....but the warning is still there.

Also, how can I tell that the scroll is working before I add more css, so far theres not really any difference in the sections I've setup

**Comment by jasonandrewth** [comment]
getting the same error

**Comment by antoinelin** [comment]
I guyz, got some hard time those lasts weeks. Gonna have free weeks so I will give a look to fix this issue. Sorry for the inconvenience. I wish you a merry Christmas 🎄
