### ISSUE TITLE
Flickering on Google Chrome v94

### ISSUE THREAD

**Issue by kirubelaklilu1** [toinelin/react-locomotive-scroll#21]
The issue is described on the main LocomotiveScroll Github [here ](https://github.com/locomotivemtl/locomotive-scroll/issues/353). 

There is a temporary fix noted [here](https://github.com/locomotivemtl/locomotive-scroll/issues/353#issuecomment-956035123), please add this to documentation or this package.

**Comment by antoinelin** [comment]
Done thank you
