### ISSUE TITLE
Compatibility with react 18

### ISSUE THREAD

**Issue by GripenANM** [toinelin/react-locomotive-scroll#26]
Is it possible to update this to support react 18?

**Comment by 0xbul1** [comment]
same err with me 

```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: website-homepage@0.0.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from react-locomotive-scroll@0.2.0
```

**Comment by faha1999** [comment]
### It is not Compatible with react 18. Update **ASAP** please

<pre><span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">code</font> ERESOLVE
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">ERESOLVE</font> unable to resolve dependency tree
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> While resolving: <b>test</b>@<b>0.1.0</b>
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Found: <b>react</b>@<b>18.1.0</b>
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> node_modules/react
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>   <b>react</b>@&quot;<b>^18.1.0</b>&quot; from the root project
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Could not resolve dependency:
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">peer</font> <b>react</b>@&quot;<b>^17.0.2</b>&quot; from <b>react-locomotive-scroll</b>@<b>0.2.0</b>
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> node_modules/react-locomotive-scroll
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>   <b>react-locomotive-scroll</b>@&quot;<b>*</b>&quot; from the root project
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Fix the upstream dependency conflict, or retry
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> this command with --force, or --legacy-peer-deps
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> to accept an incorrect (and potentially broken) dependency resolution.
</pre>

**Comment by natedin** [comment]
try:

`npm i react-locomotive-scroll --legacy-peer-deps`

**Comment by antoinelin** [comment]
Hi @faha1999 I update this repo when I have free time for it. If you want something ASAP fork the project and do it yourself.
