### ISSUE TITLE
Bug: Scroll position is preserved on previous page

### ISSUE THREAD

**Issue by ghost** [toinelin/react-locomotive-scroll#34]
This bug seems to be persistent. When I go to another page that I scroll down a bit and click the button to go back, the page keeps the position of the old page, even when using scrollTo(0, ...);

------

This bug is similar to the issue #9

**Comment by justinthomas0789** [comment]
> onLocationChange={scroll => scroll.scrollTo(0, { duration: 0, disableLerp: true })}

  Add this to your LocomotiveScrollProvider component. It will fix the issue

Eg:

> <LocomotiveScrollProvider
>   options={
>     {
>       smooth: true,
>       // ... all available Locomotive Scroll instance options 
>     }
>   }
>   watch={
>     [
>       //...all the dependencies you want to watch to update the scroll EXCEPT the location one
>     ]
>   }
>   location={asPath}
>   containerRef={containerRef}
>   onLocationChange={scroll => scroll.scrollTo(0, { duration: 0, disableLerp: true })} // If you want to reset the scroll position to 0 for example
>   onUpdate={() => console.log('Updated, but not on location change!')} // Will trigger on 
> \>
> \<main data-scroll-container ref={containerRef}\>
>     {/* ...your app */}
>   \</main\>
> \</LocomotiveScrollProvider\>

If this solution not working, try to destroy and initialise scroll onLocationChange

> onLocationChange={scroll => {scroll.destroy(); scroll.init()}}

**Comment by ghost** [comment]
Nop, this solution don't work... 

The bug still not fixed. When I click to the back btn in opera, the page keeps the position of the old page... See below :
https://vimeo.com/737984974

The code in my _app.jsx file :
```JSX
import '../styles/globals.css'
import Head from 'next/head'
import { useRef } from 'react';
import { useRouter } from 'next/router';

import { LocomotiveScrollProvider } from 'react-locomotive-scroll'

function MyApp({ Component, pageProps }) {
  const containerRef = useRef(null);
  const { asPath } = useRouter();

  return (
    <>
      <Head>
        <title>Test</title>
      </Head>   
      <LocomotiveScrollProvider
        options={
          {
            smooth: true,
            resetNativeScroll: false
            // ... all available Locomotive Scroll instance options 
          }
        }
        watch={
          [
            //..all the dependencies you want to watch to update the scroll.
            //  Basicaly, you would want to watch page/location changes
            //  For exemple, on Next.js you would want to watch properties like `router.asPath` (you may want to add more criterias if the instance should be update on locations with query parameters)
          ]
        }
        location={asPath}
        containerRef={containerRef}
        onLocationChange={scroll => {
          scroll.destroy(); 
          scroll.init();
          scroll.scrollTo(0, { duration: 0, disableLerp: true });
        }} // If you want to reset the scroll position to 0 for example
        onUpdate={scroll => {
          console.log(scroll)
        }} // Will trigger on 
      >
        <div data-scroll-container ref={containerRef}>
          <header>TEST</header>
          <main>
            <Component {...pageProps} />  
          </main>
        </div>
      </LocomotiveScrollProvider>
    </>
  )
}

export default MyApp
```

I use locomotive scroll with next.js 12.2.3 (with react 18.2.0)

**Comment by ghost** [comment]
It's okay, juste missing to set `data-scroll-section` somewhere ;)
