### ISSUE TITLE
issues with react-lazy-load-image-component

### ISSUE THREAD

**Issue by koraysels** [toinelin/react-locomotive-scroll#4]
i have some issues i cannot seem to wrap my head arround. 

I would really like to use locomotivescroll but I am getting all sorts of weird whitespace etc .. 

I think the issue lies with lazyloading images and components.. 

I already update the scroll after the lazyload has happened but when I switch pages in my gatsby app with page transitions ( `react-transition-group`) AND also without transitions..  I get all sorts of lengths of whitespace at the bottom... 
```
 <LazyLoadImage
                    effect="opacity"
                    src={page.about.picture.sourceUrl}
                    srcSet={page.about.picture.srcSet}
                    afterLoad={() => scroll.update()}
                />
```

**Comment by antoinelin** [comment]
Hello, late answer sorry,

Could you give me a reproductible environnement ? It may be depending on `locomotive-scroll` itself. It seems related to [https://github.com/toinelin/react-locomotive-scroll/issues/3](https://github.com/toinelin/react-locomotive-scroll/issues/3).
Did you try to force different React `keys` to tell React that the element is different from previous render (could help idk) ?
