### ISSUE TITLE
Improvement: Debounce height useResizeObserver

### ISSUE THREAD

**Issue by fcisio** [toinelin/react-locomotive-scroll#6]
Howdy 👋
I haven't dived very deep into this package, and it seems to work flawlessly for me so far.

But looking at the code, I think that implementing a debounce on the `height` observer would be a nice performance boost.

Most of the components impacting the height of the container will have some sort of transition, so duration and easing.
This mean's that the `scroll.update()` is triggered a bunch of times while the transition happens.

You can think of collapsible components for instance.
Thanks.

**Comment by antoinelin** [comment]
Hello @fcisio Thank you very much for your help ! Sorry I did not find time yet to check all you added to the repo. I will merge this all during the week if it is not urgent for your needs. 🙏 🙏 🙏

**Comment by antoinelin** [comment]
Merged 💪💪💪
