### ISSUE TITLE
Bug: Scroll position is preserved between pages

### ISSUE THREAD

**Issue by fcisio** [toinelin/react-locomotive-scroll#9]
Hey, I noticed a pretty significant issue.
Basically, the scroll position is preserved between pages/routes.

The container height does seem to update, and the scrollbar behaves normally.

**Current behavior:**

- From page has a scroll position of `y: 1145`
- To page lands on scroll position of `y: 1145`

**Expected behavior:**

When landing on a new page, the scroll position should be `0, 0` (top of the page).

- From page has a scroll position of `y: 1145`
- To page lands on scroll position of `y: 0`

If you need more info can draft a repro, thanks

**Comment by antoinelin** [comment]
👋🏻 I have not added this feature yet since you can use `scrollTo` on page transition by watching page change on a `useEffect`. IMO it may be a good idea to add a bit of abstraction here by adding like `scrollPosition: "preserve"|"reset"` in the provider props.

**Comment by fcisio** [comment]
Hey, thanks for the quick answer!

Yeah `scrollPosition: "preserve"|"reset"` is a good idea. Having `reset` as the default would probably best.
That way, it would be possible to use the package without page transitions.

We would need to have a new `location` prop, since want to target only the location changes.
Ex: location={location} watch={[location, ...watch]}

**Comment by antoinelin** [comment]
🖖🏻 I did not forget this, will work on it this week

**Comment by fcisio** [comment]
No worries haha,
I have a wrapper component around the package anyway, so I was able to handle this on the user side.

I ended up creating two new props, that are pretty useful.

```js
onLocation={({ scroll }) => scroll.scrollTo(0, { duration: 0, disableLerp: true })}
// onUpdate={}
```

**Comment by ElleFioLange** [comment]
For anyone else struggling with this, here's the fix I am using. I created a `<ResetScroll>` component which does its name. I wrap the main container in the `<ResetScroll>` component, which is inside of the `<LocomotiveScrollProvider>` component.
```
import { NextComponentType } from "next";
import { useEffect } from "react";
import { useLocomotiveScroll } from "react-locomotive-scroll";
import { useRouter } from "next/router";

const ResetScroll: NextComponentType = ({ children }) => {
  const { scroll } = useLocomotiveScroll();
  const { pathname } = useRouter();

  useEffect(() => {
    scroll &&
      scroll.scrollTo("top", {
        duration: 0,
        disableLerp: true,
      });
  });

  return <>{children}</>;
};

export default ResetScroll;
```

```
function MyApp({ Component, pageProps }: AppProps) {
  const { scroll, isReady } = useLocomotiveScroll();
  const containerRef = useRef(null);
  const { pathname } = useRouter();

  useEffect(() => {
    isReady && scroll.scrollTo(0, 0);
    console.log(isReady);
    console.log(pathname);
  }, [scroll, pathname, isReady]);

  return (
    <LocomotiveScrollProvider
      options={{
        touchMultiplier: 1,
        reloadOnContextChange: true,
        smooth: true,
        direction: "horizontal",
        gestureDirection: "both",
        smartphone: {
          smooth: true,
          direction: "vertical",
          gestureDirection: "both",
        },
        tablet: {
          smooth: true,
          direction: "vertical",
          gestureDirection: "both",
        },
        resetNativeScroll: false,
      }}
      containerRef={containerRef}
      watch={[pathname]}
    >
      <Head>
        <title>Sage Fiorentino-Lange</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <ResetScroll>
        <main data-scroll-container ref={containerRef}>
          <div data-scroll-section>
            <Component {...pageProps} />
          </div>
        </main>
      </ResetScroll>
    </LocomotiveScrollProvider>
  );
}
```
I'm using NextJS but this should be applicable to any React project

**Comment by Xerosta** [comment]
This bug seems to be persistent. When I go to another page that I scroll down a bit and click the button to go back, the page keeps the position of the old page, even when using scrollTo(0, ...);
